name: build

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Workflow
        run: npm run build

      - name: Push to Repository
        uses: EndBug/add-and-commit@v9
        with:
          message: Built workflow distribution files.
          add: dist
          author_name: 'Github Workflow'
          author_email: 'no-reply@github-workflow.com'
